site_name: The Essential GRASS GIS Guide
site_description: Getting Started with GRASS GIS
site_author: Aman Chaudhary
edit_uri: edit/main/docs/


theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.top
    - search.highlight
    # - navigation.sections
    # - navigation.expand
    - content.code.copy
  logo: assets/images/grass-white-no-text.svg
  favicon: assets/images/logo.png
  palette:
    - scheme: default
      primary: green
      accent: green
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: green
      accent: green
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/amanchry
      name: GitHub
    - icon: fontawesome/brands/gitlab
      link: https://gitlab.com/amanchry
      name: GitHub
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/amanchry/
      name: LinkedIn
    - icon: fontawesome/brands/twitter
      link: https://x.com/amanchry 
      name: Twitter
    - icon: material/web
      link: https://amanchaudhary.com/
      name: Personal Website

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

  
nav:
  - Introduction: index.md
  - Installation: 2_installation.md
  - Core Concepts: 3_concepts.md
  - Getting Started: 4_quickstart.md
  - Basics: 5_basics.md
  - Raster Analysis: 6_raster_basics.md
  - Vector Operations: 7_vector_basics.md
  # - Time Series: 8_time_series.md
  - Common GRASS GIS Commands: 9_common-commands.md
  - GRASS Python Scripting: 10_scripting.md
  - Zonal Statistics: 11_zonalstats.md
  - Resources: 12_resources.md
  # - Future Topics: 13_coming-soon.md
      

    